# Generated by Django 5.1.1 on 2024-12-02 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listavideojuegos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Videojuego',
            new_name='listavideojuegos',
        ),
    ]
